env:
  node: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
  strict: error
  no-multiple-empty-lines:
  - error
  - max: 1
globals:
  require: true
